name: SamaGamesCore
main: net.samagames.core.APIPlugin
authors: [geekpower14, BlueSlime]
website: http://samagames.net/
load: STARTUP

commands:
   coins:
     description: Commandes relatives aux coins
     usage: /coins [get <joueur> |credit <joueur> <montant>|withdraw <joueur> <montant>]
   stars:
     description: Commandes relatives aux étoiles
     usage: /stars [get <joueur> |credit <joueur> <montant>|withdraw <joueur> <montant>]
   start:
     description: Démarre le jeu
     usage: /start
   bukkitrefresh:
     description: Recharge les permissions locales
     usage: /bukkitrefresh
   lag:
     description: Donne des informations sur le serveur actuel et sur les latences
     usage: /lag
   playerdata:
     description: Renvoie les playerdata d'un joueur
     usage: /playerdata <pseudo>
   bukkitdebug:
     description: Renvoie les playerdata d'un joueur
     usage: /playerdata <pseudo>
   inv:
     description: Voir l'inventaire d'un joueur
     usage: /inv <pseudo>